// <auto-generated />
using System;
using BaiTap3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BaiTap3.Migrations
{
    [DbContext(typeof(BaiTap3Context))]
    partial class BaiTap3ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BaiTap3.Models.Mark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StudentRollNumber");

                    b.Property<int>("SubjectMark");

                    b.Property<string>("SubjectName");

                    b.HasKey("Id");

                    b.HasIndex("StudentRollNumber");

                    b.ToTable("Mark");

                    b.HasData(
                        new { Id = 1, StudentRollNumber = "D00123", SubjectMark = 5, SubjectName = "Java" },
                        new { Id = 2, StudentRollNumber = "D00123", SubjectMark = 15, SubjectName = "C#" },
                        new { Id = 3, StudentRollNumber = "D001234", SubjectMark = 15, SubjectName = "Java" },
                        new { Id = 4, StudentRollNumber = "D001234", SubjectMark = 10, SubjectName = "HTML" }
                    );
                });

            modelBuilder.Entity("BaiTap3.Models.Student", b =>
                {
                    b.Property<string>("RollNumber")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<int>("Status");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("RollNumber");

                    b.ToTable("Student");

                    b.HasData(
                        new { RollNumber = "D00123", CreatedAt = new DateTime(2018, 11, 8, 14, 33, 25, 501, DateTimeKind.Local), Email = "doan@gmail.com", FirstName = "Doan", LastName = "Cong", Status = 1, UpdatedAt = new DateTime(2018, 11, 8, 14, 33, 25, 502, DateTimeKind.Local) },
                        new { RollNumber = "D001234", CreatedAt = new DateTime(2018, 11, 8, 14, 33, 25, 502, DateTimeKind.Local), Email = "doan1@gmail.com", FirstName = "Doan1", LastName = "Nguyen", Status = 1, UpdatedAt = new DateTime(2018, 11, 8, 14, 33, 25, 502, DateTimeKind.Local) },
                        new { RollNumber = "D001235", CreatedAt = new DateTime(2018, 11, 8, 14, 33, 25, 502, DateTimeKind.Local), Email = "doan2@gmail.com", FirstName = "Doan2", LastName = "Doan", Status = 1, UpdatedAt = new DateTime(2018, 11, 8, 14, 33, 25, 502, DateTimeKind.Local) }
                    );
                });

            modelBuilder.Entity("BaiTap3.Models.Mark", b =>
                {
                    b.HasOne("BaiTap3.Models.Student", "Student")
                        .WithMany("Marks")
                        .HasForeignKey("StudentRollNumber");
                });
#pragma warning restore 612, 618
        }
    }
}
